name: CI

on:
  push:
    branches:
      - main

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: lilia
      - uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: "5.2"
      - uses: leafo/gh-actions-luarocks@v4.0.0
      - run: |
          luarocks install luafilesystem
          luarocks install argparse
      - uses: actions/checkout@v3
        with:
          repository: LiliaFramework/GluaCheck
          path: luacheck
      - run: |
          cd luacheck
          luarocks make
      - run: |
          cd lilia
          luacheck . \
            --no-redefined \
            --no-global --no-self \
            --no-max-line-length --no-max-code-line-length \
            --no-max-string-line-length --no-max-comment-line-length \
            --no-max-cyclomatic-complexity

  release:
      : linter
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: lilia
      - uses: actions/github-script@v6
        with:
          script: |
            const tag = 'release';
            try {
              const rel = await github.rest.repos.getReleaseByTag({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag
              });
              await github.rest.repos.deleteRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: rel.data.id
              });
              await github.rest.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `tags/${tag}`
              });
            } catch (error) {
              if (error.status !== 404) throw error;
            }
      - run: |
          mkdir packaged
          cp -R lilia packaged/lilia
          cd packaged
          zip -r ../lilia.zip lilia
      - id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: release
          release_name: Lilia
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.LiliaGitSecret }}
      - uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: lilia.zip
          asset_name: lilia.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.LiliaGitSecret }}

  deploy-pages:
    runs-on: ubuntu-latest
    needs: [linter, release]
    steps:
      - uses: actions/checkout@v3
        with:
          path: lilia
      - uses: actions/checkout@v3
        with:
          repository: LiliaFramework/LiliaFramework.github.io
          path: site
          token: ${{ secrets.LiliaGitSecret }}
      - run: |
          cp -R lilia/docs/. site
      - run: |
          cd site
          git config user.email "githubactions@github.com"
          git config user.name "GitHub Actions"
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Update docs"
            git push origin HEAD
          fi